#	DIRS
	OBJDIR			= OBJS/

	COMMONDIR		= ../../COMMON/
	
	FWAKEDIR		= $(COMMONDIR)FWake/
	FWAKEBASEDIR	= $(FWAKEDIR)FWakeBase/
	FWAKEMASTERDIR	= $(FWAKEDIR)FWakeMaster/
	
	FCRCLIBDIR		= $(COMMONDIR)FCRCLib/
	
	CONFIGSDIR		= ../../CONFIGS/
	
	
	
	DIRS		= ./
	DIRS		+= $(COMMONDIR)
	DIRS		+= $(FWAKEBASEDIR)
	DIRS		+= $(FWAKEMASTERDIR)
	
	DIRS		+= $(FCRCLIBDIR)
	
	DIRS		+= $(CONFIGSDIR)
